spring:
  datasource:
    url: jdbc:h2:~/firstms
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
      settings.trace: false
      settings.web-allow-others: false